AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 54

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
