require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/*.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Lint/ConstantDefinitionInBlock:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false
