AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 54

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'spec/*.rb'

Style/FormatStringToken:
  EnforcedStyle: template

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false


